import React, { useState } from 'react';
import { Navbar, Nav, Container } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import DonationList from './DonationList';
import VotingList from './VotingList';
import Head from 'next/head';
import Wallet from './wallet';
import Documentation from './documentation';

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<string>('home');
  const [expanded, setExpanded] = useState<boolean>(false);

  const handleNavSelect = (selectedKey: string | null) => {
    if (selectedKey) {
      setCurrentView(selectedKey);
      setExpanded(false); // Collapse the navbar after selecting a link
    }
  };

  return (
    <div style={{ fontFamily: 'Arial, sans-serif' }}>
      <Head>
        <title>Lagoon Dapps</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/images/logo icon only green.png" rel="icon" />
      </Head>

      <header className="sticky-top bg-success shadow-sm">
        <Container fluid>
          <Navbar expand="lg" className="p-3" expanded={expanded}>
            <Navbar.Brand href="#" className="text-white d-flex align-items-center">
              <img
                src="/images/logo landscape lagoon white.png"
                alt="Lagoon Logo"
                style={{ height: '100px', marginRight: '10px' }}
              />
            </Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" onClick={() => setExpanded(!expanded)} />
            <Navbar.Collapse id="basic-navbar-nav" className="justify-content-end">
              <Nav activeKey={currentView} onSelect={handleNavSelect}>
                <Nav.Link
                  eventKey="home"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Home
                </Nav.Link>
                <Nav.Link
                  eventKey="donation-list"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Lagoon List
                </Nav.Link>
                <Nav.Link
                  eventKey="voting-list"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Voting
                </Nav.Link>
                <Nav.Link
                  eventKey="documentation"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Documentation
                </Nav.Link>
              </Nav>
              <div className="ml-auto">
                <div onClick={() => setExpanded(false)}>
                  <Wallet />
                </div>
              </div>
            </Navbar.Collapse>
          </Navbar>
        </Container>
      </header>

      <main className="container mt-5">
        {currentView === 'home' && (
          <>
            <section
              className="hero-section text-center text-white mb-5 p-5 rounded shadow"
              style={{ backgroundColor: '#9DDE8B' }}
            >
              <div className="container">
                <img
                  src="/images/decentral_logo-removebg-preview.png"
                  alt="Lagoon Image"
                  className="interactive-image"
                />
                <h1 className="display-4">Welcome to Lagoon Dapps</h1>
                <p className="lead">The ultimate platform for decentralized waqf and more.</p>
              </div>
            </section>

            <section className="features-section text-center mb-5">
              <div className="container">
                <div className="row">
                  <div className="col-md-4 d-flex align-items-center justify-content-center">
                    <div className="feature-card card p-4 border-0 shadow-sm text-center">
                      <img
                        src="/images/secure_icon-removebg-preview.png"
                        alt="Secure Transactions"
                        className="interactive-image"
                      />
                      <h3>Secure Transactions</h3>
                      <p>Experience the safety and transparency of blockchain technology.</p>
                    </div>
                  </div>
                  <div className="col-md-4 d-flex align-items-center justify-content-center">
                    <div className="feature-card card p-4 border-0 shadow-sm text-center">
                      <img
                        src="/images/low_fee_icon-removebg-preview.png"
                        alt="Low Fees"
                        className="interactive-image"
                      />
                      <h3>Low Fees</h3>
                      <p>Enjoy minimal transaction fees for all your donations.</p>
                    </div>
                  </div>
                  <div className="col-md-4 d-flex align-items-center justify-content-center">
                    <div className="feature-card card p-4 border-0 shadow-sm text-center">
                      <img
                        src="/images/global_icon-removebg-preview.png"
                        alt="Global Reach"
                        className="interactive-image"
                      />
                      <h3>Global Reach</h3>
                      <p>Make a difference worldwide with our decentralized platform.</p>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </>
        )}

        {currentView === 'donation-list' && <DonationList />}
        {currentView === 'voting-list' && <VotingList />}
        {currentView === 'documentation' && <Documentation />}
      </main>

      <footer className="text-white p-3 mt-5 bg-success shadow-sm">
        <div className="container text-center">
          <p className="mb-0">&copy; 2024 Lagoon Dapps. All rights reserved.</p>
        </div>
      </footer>

      <style jsx>{`
        .nav-item-hover {
          transition: background-color 0.3s ease, color 0.3s ease;
          border-radius: 5px;
        }
        .nav-item-hover:hover {
          background-color: #28a745;
          color: #fff;
        }
        .interactive-image {
          max-width: 70%;
          height: auto;
          margin-bottom: 20px;
          margin: 0 auto;
          display: block;
          transition: transform 0.3s ease;
        }
        .interactive-image:hover {
          transform: scale(1.1);
        }
        @media (max-width: 768px) {
          .navbar-collapse {
            background-color: #28a745;
            padding: 10px;
            border-radius: 5px;
            transition: height 0.3s ease;
          }
          .navbar-nav .nav-link {
            color: #fff !important;
            padding: 10px 15px;
            border-radius: 5px;
            transition: background-color 0.3s ease, color 0.3s ease;
          }
          .navbar-nav .nav-link:hover {
            background-color: #218838;
          }
        }
      `}</style>
    </div>
  );
};

export default App;
