import React, { useState, useEffect } from 'react';
import { Navbar, Nav, Container, Spinner } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import DonationList from './DonationList';
import VotingList from './VotingList';
import RealEstateWaqf from './realEstateWaqf';
import Head from 'next/head';
import Wallet from './wallet';
import Documentation from './documentation';

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<string>('home');
  const [expanded, setExpanded] = useState<boolean>(false);
  const [loading, setLoading] = useState(true);

  const handleNavSelect = (selectedKey: string | null) => {
    if (selectedKey) {
      setCurrentView(selectedKey);
      setExpanded(false);
    }
  };

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, []);

  return (
    <div style={{ fontFamily: 'Arial, sans-serif' }}>
      <Head>
        <title>Lagoon Dapps</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/images/logo icon only green.png" rel="icon" />
      </Head>

      <header className="sticky-top bg-success gradient-bg">
        <Container fluid>
          <Navbar expand="lg" className="p-3" expanded={expanded}>
            <Navbar.Brand className="text-white d-flex align-items-center">
              <img
                src="/images/logo landscape lagoon white.png"
                alt="Lagoon Logo"
                style={{ height: '100px', marginRight: '10px' }}
              />
            </Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" onClick={() => setExpanded(!expanded)} />
            <Navbar.Collapse id="basic-navbar-nav" className="justify-content-end">
              <Nav activeKey={currentView} onSelect={handleNavSelect}>
                <Nav.Link
                  eventKey="home"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Home
                </Nav.Link>
                <Nav.Link
                  eventKey="donation-list"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Lagoon List
                </Nav.Link>
                <Nav.Link
                  eventKey="voting-list"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Lagoon Vote
                </Nav.Link>
                <Nav.Link
                  eventKey="asset-tokenization"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Lagoon Tokenization
                </Nav.Link>
                <Nav.Link
                  eventKey="documentation"
                  className="text-white px-3 nav-item-hover"
                  style={{ cursor: 'pointer' }}
                >
                  Documentation
                </Nav.Link>
              </Nav>
              <div className="ml-auto">
                <div onClick={() => setExpanded(false)}>
                  <Wallet />
                </div>
              </div>
            </Navbar.Collapse>
          </Navbar>
        </Container>
      </header>

      <div className="palebg">
        <main className="container">
          {loading ? (
            <div className="d-flex justify-content-center">
              <Spinner animation="border" variant="success" />
            </div>
          ) : currentView === 'home' ? (
            <>
              <section
                className="hero-section text-center text-white mb-5 p-5 rounded shadow gradient-bg"
                style={{ backgroundColor: '#F6FFDE' }}
              >
                <div className="container">
                  <img
                    src="/images/decentral_logo-removebg-preview.png"
                    alt="Lagoon Image"
                    className="interactive-image"
                  />
                  <h1 className="display-4">Welcome to Lagoon Dapps</h1>
                  <p className="lead">The ultimate platform for decentralized waqf and charity.</p>
                </div>
              </section>
            </>
          ) : currentView === 'donation-list' ? (
            <DonationList />
          ) : currentView === 'voting-list' ? (
            <VotingList />
          ) : currentView === 'asset-tokenization' ? (
            <RealEstateWaqf />
          ) : currentView === 'documentation' ? (
            <Documentation />
          ) : null}
        </main>
      </div>

      <footer className="text-white p-3 bg-success backwardgradient-bg">
        <div className="container text-center">
          <p className="mb-0">&copy; 2024 Lagoon Dapps. All rights reserved.</p>
        </div>
      </footer>

      <style jsx>{`
        .palebg {
          background: #f6ffde;
        }

        .gradient-bg {
          background: linear-gradient(to bottom, #28a745, #f6ffde);
        }

        .backwardgradient-bg {
          background: linear-gradient(to top, #28a745, #f6ffde);
        }

        .nav-item-hover {
          transition: background-color 0.3s ease, color 0.3s ease;
          border-radius: 5px;
        }
        .nav-item-hover:hover {
          background-color: #f6ffde;
          color: #fff;
        }

        .interactive-image {
          max-width: 70%;
          margin: 20px auto;
          display: block;
          transition: transform 0.3s ease;
        }
        .interactive-image:hover {
          transform: scale(1.1);
        }

        .hero-section {
          animation: fadeInUp 1s ease-in-out;
        }
        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @media (max-width: 768px) {
          .navbar-collapse {
            background-color: #28a745;
            padding: 10px;
            border-radius: 5px;
          }
          .navbar-nav .nav-link {
            color: #fff;
            padding: 10px 15px;
          }
          .navbar-nav .nav-link:hover {
            background-color: #218838;
          }
        }
      `}</style>
    </div>
  );
};

export default App;
